config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "books#index"
  resources :books, only: [:index, :new, :create, :edit, :update, :show, :destroy]

  resources :users, only: [:show, :new, :create]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # ex of method you might want: .random, now every ORM class has a random method
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :quantity, presence: true
  validates :price, presence: true

  belongs_to :user
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :most_recent_book, :current_user

  def most_recent_book
    if current_user.books.exists?(session[:most_recent_book])
      current_user.books.find(session[:most_recent_book_id])
    elsif current_user.books.last
      current_user.books.last
    else
      Book.new(title: "YOU HAVEN'T MADE A BOOK YET")
    end
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
  # we could put methods we want across all controllers
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :do_the_thing, only: [:show, :index]

  def index
    if current_user
      @books = current_user.books.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
    @categories = Category.all
  end

  def edit
    @book = Book.find( params[:id] )
    @categories = Category.all
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      flash[:notice] = "The book #{@book.title} was created"
      session[:most_recent_book_id] = @book.id
      redirect_to book_path(@book)
    else
      flash[:error] = @book.errors.full_messages.join(", ")
      render :new
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    session[:most_recent_book_id] = Book.last.id

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :price, :quantity, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to books_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.label :quantity %>
  <%= f.text_field :quantity %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :name %>

  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form" %>

app/views/books/index.html.erb
<%= link_to "Add New Book to the Shelf", new_book_path %>

<% if @books %>
<ul>
  <% @books.each do |book| %>
    <!-- <h2><%= book.title %></h2>
    <p>
      $<%= book.price %>, we have <%= book.quantity %>
    </p> -->
    <h2><%= link_to book.title, book_path(book) %></h2>
    <li>
      $<%= book.price %> - <%= book.quantity %> copies
    </li>
  <% end %>

</ul>
<% else %>
  <h3>We are sorry, there are no books. Please login and add some!</h3>
<% end %>

app/views/books/new.html.erb
<%= render partial: "form" %>

app/views/books/show.html.erb
<div class="book_info">
  <h2><%= @book.title %></h2>

  <p>
    Price: $<%= @book.price %>
  </p>

  <p>
    Quantity: <%= @book.quantity %>
  </p>
  <% if @book.user %>
    <p>
      This book belongs to <%= @book.user.username %>
    </p>
  <% end %>
</div>
<h3><%= link_to "Edit Book Properties", edit_book_path(@book) %></h3>
<h3><%= link_to "Burn the Book (you monster)", book_path(@book), method: :delete %></h3>
<h3><%= link_to "Back to Books", books_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookShelf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "flash_#{name}" %>
    <% end %>
    <p>
    </p>
    <% if current_user %>
      <p>
        The current user is <strong><%= current_user.username %></strong> <br />
        <strong>Newest Book: <%= most_recent_book.title %></strong>
      </p>
    <% end %>
    <%= yield %>
    <% if current_user %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", login_path %>
    <% end %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br />

  <%= f.label :username %>
  <%= f.text_field :username %> <br />

  <%= f.label :password %>
  <%= f.password_field :password %> <br />

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> <br />

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h2>Welcome, <%= @user.username %></h2>

<%= link_to "Your books", books_path %>